apiVersion: v1
kind: Secret
metadata:
  name: nexent-infrastructure-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  ELASTIC_PASSWORD: {{ .Values.secrets.elasticPassword | b64enc | quote }}
  NEXENT_POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | b64enc | quote }}
  MINIO_ROOT_USER: {{ .Values.secrets.minio.rootUser | b64enc | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.secrets.minio.rootPassword | b64enc | quote }}
  MINIO_ACCESS_KEY: {{ .Values.secrets.minio.accessKey | b64enc | quote }}
  MINIO_SECRET_KEY: {{ .Values.secrets.minio.secretKey | b64enc | quote }}
