export interface ConversationListItem {
  conversation_id: number;
  conversation_title: string;
  agent_id?: number | null;
  create_time: number;
  update_time: number;
}

export interface ConversationListParams {
  offset: number;
  limit: number;
}

export interface ConversationListResponse {
  code: number;
  data: ConversationListPage;
  message: string;
}

export interface ConversationListMetadata {
  total: number;
  today: number;
  last_7_days: number;
  older: number;
}

export interface ConversationListPage {
  items: ConversationListItem[];
  metadata: ConversationListMetadata;
}

export interface ApiMessageItem {
  type: string;
  content: string;
  unit_index?: number;
  unit_status?: "streaming" | "completed";
  tool_call_id?: string;
  role?: string;
  tool_name?: string;
  tool_arguments?: string | Record<string, unknown>;
  // Stable sub-agent invocation id (UUID4) generated by the SDK wrapper.
  // Persisted alongside ``subagent_start`` / ``subagent_end`` units so the
  // frontend can rebuild parallel sub-agent boundaries deterministically.
  invocation_id?: string;
  agent_id?: number | string;
  agent_name?: string;
  depth?: number;
}

export interface ApiMessage {
  role: "user" | "assistant";
  message: ApiMessageItem[] | string;
  message_id?: number;
  message_index?: number;
  create_time?: number | null;
  picture?: string[];
  search?: any[];
  searchByUnitId?: Record<string, any[]>;
  minio_files?: Array<
    | string
    | {
        object_name: string;
        name: string;
        type: string;
        size: number;
        url?: string;
        presigned_url?: string;
        preview_url?: string;
        download_url?: string;
      }
  >;
}

export interface StreamingMessage {
  message_id: number;
  message_index: number;
  status: "streaming";
  message_content: string;
  last_unit?: ApiMessageItem;
  units: ApiMessageItem[];
}

export interface ApiConversationDetail {
  create_time: number;
  // The history endpoint currently serializes this id as a string, while
  // other conversation endpoints return a number.
  conversation_id: number | string;
  conversation_title?: string;
  agent_id?: number | null;
  chat_mode?: "planning" | "execution";
  knowledge_scope?:
    | import("./knowledgeScope").ConversationKnowledgeScope
    | null;
  runtime_metadata?: Record<string, unknown>;
  runtime_metadata_version?: number;
  message: ApiMessage[];
  streaming_message?: StreamingMessage;
}

export interface ApiConversationResponse {
  code: number;
  data: ApiConversationDetail[];
  message: string;
}
